### ISSUE TITLE
Fix linux sound output as aplay does not work, swap for something else

### ISSUE THREAD

**Issue by jestarray** [racket/gui#239]
so this does not work on both Arch Linux with prebuilt racket binaries and Debian with built from source binaries(according to a user JSGRANT on the racket discord server https://discord.com/channels/571040468092321801/618895179343986688/879797867903057921):
```
#lang racket

(require 2htdp/image
         (only-in racket/gui/base play-sound))


(put-preferences '(GRacket:playcmd) '("mpv --no-audio-display ~a"))

; https://upload.wikimedia.org/wikipedia/commons/5/5d/Nl-honk.ogg
 (play-sound "./Nl-honk.ogg" #t)
```
because of this:
https://github.com/racket/gui/blob/8aca4a224e887175975315895a42dd05b2d9ce77/gui-lib/mred/private/misc.rkt#L79
It uses `aplay` first to try and play the sound but according to this:
https://unix.stackexchange.com/questions/363176/ogg-audio-file-and-aplay-white-noise
```
You cannot decode ogg files with aplay. According to the man page, the only formats aplay understands are voc, wav, raw and au. My guess is that aplay interprets the ogg file as raw data, hence the white noise.
```

so I suggest swapping the order to `sndfile-play` or whichever command line audioplayer is available on most linux installations

**Comment by sorawee** [comment]
That doesn't sound right (pun not intended). 

https://github.com/racket/gui/blob/8aca4a224e887175975315895a42dd05b2d9ce77/gui-lib/mred/private/misc.rkt#L77 

says that if `cmd` is set already, then it will use the command. Are you sure it really fails because it tries to use `aplay`?

**Comment by jestarray** [comment]
@sorawee yes, I am sure.

https://user-images.githubusercontent.com/34615798/130677735-51824cdd-8887-40b4-a334-0abdfec298fb.mp4

**Comment by sorawee** [comment]
That's not what I meant. I understand that `aplay` doesn't work. What I asked is, is it really the case that Racket tries to use `aplay`, despite the fact that you have already set `GRacket:playcmd` to invoke `mpv` instead?

**Comment by jestarray** [comment]
OHH i forgot to remove that line ! thought I did....

**Comment by samdphillips** [comment]
FWIW my (mostly) default Ubuntu and Xubuntu desktop systems do not have `sndfile-play`

**Comment by samdphillips** [comment]
`paplay` may be a better cross Linux choice.

**Comment by jestarray** [comment]
On a fresh reinstall of Windows 10 May Update 2021, even sounds on Windows do not work: 
![image](https://user-images.githubusercontent.com/34615798/130687705-2d969a2e-5c0a-45bf-b828-85c1208befda.png)

mciSendStringW: The specified device is not open or is not recognized by MCI.

**Comment by mflatt** [comment]
I've pushed some repairs, including making `paplay` the first tried program on Unix-like systems.

As far as I can tell, ".ogg" files just aren't supported (without installing something extra?) on Windows, and that's the error that the MCI layer reports for a ".ogg" file.

**Comment by jestarray** [comment]
> As far as I can tell, ".ogg" files just aren't supported (without installing something extra?) on Windows, and that's the error that the MCI layer reports for a ".ogg" file.

So I tried playing a .wav file and I'm getting:
```
mciSendStringW: All wave devices that can play files in the current format are in use.  Wait until a wave device is free, and then try again.
```
Which is strange because I have nothing thats playing audio atm nor did I open any audio applications. I tried a fresh reboot and still no luck. It's probably unrelated to the .wav file but in case you want try it: https://opengameart.org/sites/default/files/vgmenuselect.wav
```
#lang racket

(require 2htdp/image
         (only-in racket/gui/base play-sound))

;https://opengameart.org/sites/default/files/vgmenuselect.wav
(play-sound "./vgmenuselect.wav" #t)
```
Can anyone else produce on Windows 10 on the May 2021 update(21h1) ?

**Comment by jestarray** [comment]
> After a few years, the MCI interface has been phased out in favor of the DirectX APIs first released in 1995.
According to: https://en.wikipedia.org/wiki/Media_Control_Interface
so it might come up again, let's just hope windows 11 doesn't phase it out completely. I think microsoft is generally ok at backwards compatibility though
